Account_Management/urls.py
from django.urls import path
from .views import AccountList, AccountSettingView, ConfigureView, \
    AddUserView, OrganizationView, InvitationView, ManageUserView, RegisterWithInvitationView, RetrieveImageView
from . import views

app_name = 'account_management'

urlpatterns = [
    path('', AccountList.as_view(), name='account'),
    path('edit_account/', AccountSettingView.as_view(), name='edit_account'),
    path('account_list/', ConfigureView.as_view(), name='account_list'),
    path('add_user/', AddUserView.as_view(), name='add_user'),
    path('invitation/', InvitationView.as_view(), name='invitation'),
    path('organization/', OrganizationView.as_view(), name='organization'),
    path('manage_users/', ManageUserView.as_view(), name='manage_users'),
    path('register/<invitation_token>/', RegisterWithInvitationView.as_view(), name='register_with_invitation'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('active_user/<int:user_id>/', views.active_user, name='active_user'),
    path('upload_image/', views.image_upload_view, name='image_upload'),
    path('retrieve/', RetrieveImageView.as_view(), name='retrieve_image'),
]

User_Management/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import ProfileList, CustomLoginView, RegisterPage, ActivateAccount, UserSettingView, ResendActivationView,\
    VerifyCodeView, UpdateEmployerLogoView
from django.contrib.auth.views import LogoutView
from . import views


urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('', ProfileList.as_view(), name='profiles'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name='User_Management/password_reset.html'),
         name='password_reset'),  # submit email form
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='User_Management/password_reset_sent.html'),
         name='password_reset_done'),  # Email sent success message
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='User_Management/password_reset_form.html'),
         name='password_reset_confirm'),  # Link to password reset form in email
    path('reset_password_complete',
         auth_views.PasswordResetCompleteView.as_view(template_name='User_Management/password_reset_done.html'),
         name='password_reset_complete'),  # Password successfully changed message
    path('delete_account/<int:account_id>/', views.delete_account, name='delete_account'),
    path('user_setting/', UserSettingView.as_view(), name='user_setting'),
    path('verify_code/', VerifyCodeView.as_view(), name='verify_code'),
    path('resend_activation/', ResendActivationView.as_view(), name='resend_activation'),
    path('update_company_name/<int:account_id>/', views.update_company_name, name='update_company_name'),
    path('upload_employer_logo/', UpdateEmployerLogoView.as_view(), name='user_avatar'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User_Management.urls')),
    path('account/', include('Account_Management.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User_Management/forms.py
from django import forms
from .models import Profile, CustomUser
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


# from django.contrib.auth.models import User


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control form-control-prepended'}),
                             label='Email'
                             )

    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-prepended'}),
        label='Username'
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-prepended'}),
        label='Password1'
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-prepended'}),
        label='Password2'
    )

    class Meta:
        model = CustomUser
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class ResendActivationEmailForm(forms.Form):
    email = forms.EmailField(required=True)


class CustonmerForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control form-control-prepended'}),
        label='Username'
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control form-control-prepended'}),
        label='Password'
    )


class UserInfoForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'shadow-border'}),
                                 max_length=200, label='First name')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'shadow-border'}),
                                max_length=200, label='Last name')


class UpdateEmailForm(forms.Form):
    new_email = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'shadow-border'}), label='new email')


class VerificationForm(forms.Form):
    verification_code = forms.CharField(widget=forms.TextInput(attrs={'class': 'shadow-border'}),
                                        max_length=20, label='Verification Code')


class UpdatePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'shadow-border'}),
                                   label="Old Password")
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'shadow-border'}),
                                    label="New Password")
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'shadow-border'}),
                                    label="Confirm New Password")


class UserLogoUrlForm(forms.Form):
    user_logo_url = forms.URLField(max_length=300, label='user_logo_url')

User_Management/views.py
import pdb
import random
import re
from django.contrib.auth import logout
from django.contrib.auth import update_session_auth_hash
from django.shortcuts import get_object_or_404, render
from django.utils.crypto import get_random_string
from django.shortcuts import redirect
from django.views.generic import View
from django.views.generic.list import ListView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy, reverse
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import send_mail
from django.contrib import messages
from .forms import UserCreationForm, CustomLoginForm, UpdateEmailForm, UserInfoForm, UpdatePasswordForm, \
    VerificationForm, ResendActivationEmailForm
from .models import Profile, CustomUser
from Account_Management.models import Account, AccountUserRelation, TeamInvitation
from django.contrib.auth.models import Group


class CustomLoginView(LoginView):
    authentication_form = CustomLoginForm
    template_name = 'User_Management/login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    
    def form_valid(self, form):
        user = form.get_user()

        if user.is_authenticated:
            user_email = user.email
            invitation_exists = TeamInvitation.objects.filter(invited_email=user_email).exists()

            if invitation_exists:
                invitation_account = TeamInvitation.objects.filter(invited_email=user_email).first()
                account_user_relation = AccountUserRelation.objects.filter(user=user).first()

                if account_user_relation:
                    account = account_user_relation.account
                    other_users_count = AccountUserRelation.objects.filter(account=account).exclude(user=user).count()
                    
                    if other_users_count == 0:
                        role_type = invitation_account.role.role_type.capitalize()
                        role_type += " Group"
                        group_instance = Group.objects.get(name=role_type)
                        user.groups.set([group_instance])
                        # Delete the old account (if desired)
                        if account_user_relation.account:
                            account_user_relation.account.delete()

                        # Assign the new account from the invitation
                        account_user_relation.account = invitation_account.account
                        account_user_relation.save()
                        
                        

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('profiles')


class RegisterPage(FormView):
    template_name = 'User_Management/signup.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('profiles')  # where user will be redirect after success registration

    # email_sent = False

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        token = default_token_generator.make_token(user)
        current_site = get_current_site(self.request)
        mail_subject = 'Activate your account'
        message = render_to_string('User_Management/account_activation_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': token,
        })
        send_mail(mail_subject, message, 'yifandsb666@gmail.com', [user.email])
        self.request.session['email_sent'] = True
        # pdb.set_trace()
        email_sent_message = "Activation email has been sent to your email address."  # flash message
        messages.success(self.request, email_sent_message)
        admin_group, created = Group.objects.get_or_create(name='Admin Group')
        user.groups.add(admin_group)
        # return redirect('resend_activation_email') #Notify about the sent in another page
        return self.render_to_response(self.get_context_data(form=form))

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('profiles')  # Redirect to the home page
        if 'email_sent' in self.request.session:
            del self.request.session['email_sent']
        # resend_verification = self.request.GET.get('resend_verification')
        # if resend_verification == 'true':
        #     return self.resend_activation_email()
        return super().get(*args, **kwargs)

    # def post(self, *args, **kwargs):
    #     if "create_account" in self.request.POST:
    #         return self.form_valid(self.get_form())  # Manually call form_valid for account creation
    #     elif "resend_verification" in self.request.POST:
    #         return self.resend_activation_email()
    #     else:
    #         return super().post(*args, **kwargs)

    # def resend_activation_email(self):
    #     if self.email_sent:
    #         user = self.request.user 
    #         if not user.is_active:
    #             token = default_token_generator.make_token(user)
    #             current_site = get_current_site(self.request)
    #             mail_subject = 'Resend Activation Email'
    #             message = render_to_string('User_Management/account_activation_email.html', {
    #                 'user': user,
    #                 'domain': current_site.domain,
    #                 'uid': urlsafe_base64_encode(force_bytes(user.pk)),
    #                 'token': token,
    #             })
    #             send_mail(mail_subject, message, 'yifandsb666@gmail.com', [user.email])
    #             email_sent_message = "Activation email has been resent to your email address."
    #             messages.success(self.request, email_sent_message)
    #         else:
    #             messages.warning(self.request, "Account is already active or user is not authenticated.")
    #     else:
    #         messages.warning(self.request, "Please submit the form first to initiate the verification email.")

    #     return self.render_to_response(self.get_context_data(form=self.form))


class ResendActivationView(FormView):
    template_name = 'User_Management/resend_activation.html'
    form_class = ResendActivationEmailForm
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = self.request.user
        try:
            user = CustomUser.objects.get(email=form.cleaned_data['email'])
        except CustomUser.DoesNotExist:
            messages.error(self.request, "No account with this email exists.")
            return super().form_valid(form)

        if not user.is_active:
            token = default_token_generator.make_token(user)
            current_site = get_current_site(self.request)
            mail_subject = 'Resend Activation Email'
            message = render_to_string('User_Management/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': token,
            })
            send_mail(mail_subject, message, 'yifandsb666@gmail.com', [user.email])
            email_sent_message = "Activation email has been resent to your email address."
            messages.success(self.request, email_sent_message)
        else:
            messages.warning(self.request, "Account is already active.")

        return super().form_valid(form)


class ActivateAccount(View):
    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = CustomUser.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
            user = None
        # pdb.set_trace()  # 断点
        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.is_staff = False
            user.profile.email_confirmed = True
            user.save()

            desired_domin = 'http://www.domin/' + get_random_string(32)
            account = Account.objects.create(company_domain=desired_domin)
            AccountUserRelation.objects.create(account=account, user=user)

            # login(request, user)
            messages.success(request, 'Your account have been confirmed.')
            return redirect('login')
        else:
            messages.warning(request, 'The confirmation link was invalid, possibly because it has already been used.')
            return redirect('register')


class ProfileList(LoginRequiredMixin, ListView):
    model = Profile
    context_object_name = 'profiles'

    def get_user_roles(self):
        user = self.request.user
        user_groups = user.groups.all()
        user_roles = [group.name for group in user_groups]
        # pdb.set_trace()  # 断点
        return force_str(user_roles)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_roles = self.get_user_roles()
        context['user_roles'] = user_roles

        # get user's firstname and lastname
        current_user = self.request.user
        first_name = current_user.first_name
        last_name = current_user.last_name

        # put firstname and lastname in context
        context['first_name'] = first_name
        context['last_name'] = last_name

        account_relation = AccountUserRelation.objects.filter(user=self.request.user).first()
        if account_relation:

User_Management/templates/User_Management/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

User_Management/templates/User_Management/password_reset.html
{% extends 'User_Management/main_1.html' %}
{% block content%}
<title>Password Reset | HireBeat</title>

</html>

<body class="layout-login-centered-boxed">


    <div class="layout-login-centered-boxed__form">
        <div class="d-flex flex-column justify-content-center align-items-center mt-2 mb-4 navbar-light">
            <a href="index.html" class="navbar-brand text-center mb-2 mr-0 flex-column" style="min-width: 0">
                <!-- LOGO -->
                <img id="icon" src="https://hirebeat-assets.s3.amazonaws.com/HireBeatLogo2.png" alt="HireBeat Logo"/> </img>
                

                <span class="mt-2">Passwrod Reset</span>
            </a>
        </div>
        <div class="card card-body">   
            <div style="margin: auto; width: 90%; font-family: Arial, Helvetica, sans-serif;">

                <p class="margin medium-small">
                Forgotten your password? Enter your email address below, and we’ll email
                instructions for setting a new one.
                </p>
            </div>
            <form method="post" autocomplete="off">
            {% csrf_token %}
                <div class="input-field col s12" style="vertical-align: middle;">
                    <i class="material-icons prefix">mail_outline</i>
                    <label for="{{ form.email.id_for_label }}" style="display: inline-block; vertical-align: middle;" id="email_label"> </label>
                    {{form.email}}
                </div>
                <div class="text-center"><br>
                    <input class="btn btn-primary mb-2"  type="submit" name="Send me instructions!" /><br>
                </div>
            </form>

            </div>
        </div>
    </div>

{% endblock content %}

User_Management/templates/User_Management/user_setting.html
{% extends 'Account_Management/account_main.html' %}
{% load static %}
{% load replace %}
{% block content %}
    <head>
        <title>User Setting| HireBeat</title>
    <style>
        .shadow-border {
            border: none;
            border-bottom: 1px solid transparent;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            background-color: #FFFFFF;
            width: 100%;
            padding: 5px;
        }

        #image {
            width: 40px;
            height: 40px;
            object-fit: cover;
            border-radius: 50%;
        }
    </style>
    </head>
    <body>
    <div class="mdk-header-layout__content mdk-header-layout__content--fullbleed mdk-header-layout__content--scrollable page" style="padding-top: 60px;">


            <div class="page__heading border-bottom">
                <div class="container-fluid page__container d-flex align-items-center">
                    <h1 class="mb-0">User Settings </h1>
{#                    <p>{{ user_roles|slice:"0:-5"|replace:"_"}}</p>#}
                </div>
            </div>

            <div class="container-fluid page__container">

                <div class="card card-form">
                    <div class="row no-gutters">
                        <div class="col-lg-4 card-body">
                            <p><strong class="headings-color">Basic Information</strong></p>
                            <p class="text-muted mb-0">Update your information.</p>
                        </div>
                        <div class="col-lg-8 card-form__body card-body">
                            <form method="post" class="form-inline">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="fname">First name</label>
                                </div>
                                <div class="form-group">
                                    {{ user_info_form.first_name }}
                                </div>

                                <div class="form-group" style="margin-left: 15px">
                                    <label for="lname">Last name</label>
                                </div>
                                <div class="form-group">
                                    {{ user_info_form.last_name }}
                                </div>
                                <div class="col">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="card card-form">
                    <div class="row no-gutters">
                        <div class="col-lg-4 card-body">
                            <p><strong class="headings-color">Profile Settings</strong></p>
                            <p class="text-muted mb-0">Update your logo and video here.</p>
                        </div>
                        <div class="col-lg-8 card-form__body card-body">
                            <div class="form-group">
                                <label style="margin-left: 16px">Avatar</label></br>

                                <form method="post" action="{% url 'user_setting' %}">
                                    {% csrf_token %}
                                    <div class="col">
{#                                        <button id="upload" onclick="uploadImage()" class="btn btn-primary" style="margin-top: 20px">Upload</button>#}
                                        <input type="file" id="photo" onchange="uploadImage()"/></br>
                                        <img id="image" src="{{ user.user_logo }}"  alt="Not set yet" style="margin-top: 20px">
                                        <input type="url" name="user_logo" required class="shadow-border"  value="{{ user.user_logo }}" style="margin-top: 20px">
                                        <div class="text-right mb-5">
                                            <input class="btn btn-primary" type="submit" value="Submit" style="margin-top: 20px; margin-right: 650px">
                                        </div>
                                    </div>
                                </form>
                                <input id="accountName" type="hidden" value="{{ account.company_name }}">
                                <input id="userName" type="hidden" value="{{ user.first_name }}_{{ user.last_name }}">
                            </div>

                        </div>
                    </div>
                </div>

                <div class="card card-form">
                    <div class="row no-gutters">
                      <div class="col-lg-4 card-body">
                        <p><strong class="headings-color">Update Your Email</strong></p>
                        <p class="text-muted mb-0">Change your Email.</p>
                      </div>
                      <div class="col-lg-8 card-form__body card-body">
                        <div class="row">
                          <div class="col-md-6">
                              <form method="post" class="form-inline">
                                  {% csrf_token %}
                                  <div class="form-group">
                                      <label for="npass">New Email:</label>
                                      {{ update_email_form.new_email }}
                                  </div>
                                  <div class="col" style="margin-top: 15px">
                                    <button type="submit" class="btn btn-primary">Change</button>
                                  </div>
                                  <div style="margin-top: 20px">
                                      {%for message in messages %}
                                         {%if "email" in message.tags %}
                                              <p> {{message}} </p>
                                         {%endif%}
                                      {%endfor%}
                                  </div>
                              </form>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>

                <div class="card card-form">
                    <div class="row no-gutters">
                      <div class="col-lg-4 card-body">
                        <p><strong class="headings-color">Update Your Password</strong></p>
                        <p class="text-muted mb-0">Change your password.</p>
                      </div>
                      <div class="col-lg-8 card-form__body card-body">
                        <div class="row">
                          <div class="col-md-6">
                              <form method="post" class="form-inline">
                                  {% csrf_token %}
                                  <div class="form-group">
                                      <label for="opass">Old Password:</label>
                                      {{ update_password_form.old_password }}
                                  </div>

                                  <div class="form-group" style="margin-top: 20px">
                                      <label for="npass">New Password:</label>
                                      {{ update_password_form.new_password1 }}
                                      <small class="invalid-feedback">The new password must not be empty.</small>
                                  </div>

                                  <div class="form-group" style="margin-top: 20px">
                                      <label for="cpass">Confirm Password:</label>
                                      {{ update_password_form.new_password2 }}
                                  </div>
                                  <div class="col">
                                      <button type="submit" class="btn btn-primary" style="margin-top: 20px">Save</button>
                                  </div>
                                  <div style="margin-top: 20px">
                                      {%for message in messages %}
                                         {%if "password" in message.tags %}
                                              <p> {{message}} </p>
                                         {%endif%}
                                      {%endfor%}
                                  </div>
                              </form>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>

                <div class="text-right mb-5">
                    <a href="{% url 'account_management:account'%}" class="btn btn-success">Go Back</a>
                </div>
            </div>
{#        <input type="file" id="photo" /></br>#}
{#        <button id="upload" onclick="uploadImage()">Upload</button>#}
{#        <img id="image" src="" >#}

        </div>
        <script src="https://www.gstatic.com/firebasejs/7.7.0/firebase-app.js"></script>
        <script src="https://www.gstatic.com/firebasejs/7.7.0/firebase-storage.js"></script>
        <script>

           //paste here your copied configuration code
           const firebaseConfig = {
              apiKey: "AIzaSyBxYu2sNjLgQsJJ7PwyK228DDdgg4rgSTw",
              authDomain: "hirebeat-561be.firebaseapp.com",
              projectId: "hirebeat-561be",
              storageBucket: "hirebeat-561be.appspot.com",
              messagingSenderId: "100708272950",
              appId: "1:100708272950:web:7fbab5c81409113efd8197",
              measurementId: "G-56Z0DL0SH3"
           };

           // Initialize Firebase
           firebase.initializeApp(firebaseConfig);
           console.log(firebase);

           function uploadImage() {
              const ref = firebase.storage().ref();
              const file = document.querySelector("#photo").files[0];
              const accountName = document.getElementById("accountName").value;
              const userName = document.getElementById("userName").value;
              const name = accountName + '_' + userName
               const metadata = {
                 contentType: file.type
              };
              const task = ref.child("logo/user/" + name).put(file, metadata);
              task.then(snapshot => snapshot.ref.getDownloadURL())
              .then(url => {
                  console.log(url);
                  alert('image uploaded successfully');
                  document.querySelector("#image").src = url;

                  getDownloadURLForImage("logo/user/" + name);
                })
               .catch(console.error);
               }

           function getDownloadURLForImage(imagePath) {
              const storageRef = firebase.storage().ref();
              const imageRef = storageRef.child(imagePath);
              var userLogoInput = document.querySelector('input[name="user_logo"]');

              imageRef.getDownloadURL()
                  .then((url) => {
                     console.log("Image URL:", url);
                     document.querySelector("#image").src = url;
                     userLogoInput.value = url;
                  })
                  .catch((error) => {
                     console.error("Error getting download URL:", error);
                  });
           }
        </script>
        <script>
            const newPassword1 = document.getElementById('new_password1');
            const newPassword2 = document.getElementById('new_password2');
            const passwordMismatchMsg = document.getElementById('password_mismatch');

            newPassword2.addEventListener('input', function() {
                if (newPassword1.value !== newPassword2.value) {
                    passwordMismatchMsg.style.display = 'block';
                } else {
                    passwordMismatchMsg.style.display = 'none';
                }
            });
        </script>

    <!-- App Settings FAB -->
    <div id="app-settings">
        <app-settings layout-active="default" :layout-location="{
      'default': 'edit-account.html',
      'fixed': 'fixed-edit-account.html',
      'fluid': 'fluid-edit-account.html',
      'mini': 'mini-edit-account.html'
    }"></app-settings>
    </div>
    </body>
{% endblock content %}