Account_Management/urls.py
from django.urls import path
from .views import AccountList, AccountSettingView, ConfigureView, \
    AddUserView, OrganizationView, InvitationView, ManageUserView, RegisterWithInvitationView, RetrieveImageView
from . import views

app_name = 'account_management'

urlpatterns = [
    path('', AccountList.as_view(), name='account'),
    path('edit_account/', AccountSettingView.as_view(), name='edit_account'),
    path('account_list/', ConfigureView.as_view(), name='account_list'),
    path('add_user/', AddUserView.as_view(), name='add_user'),
    path('invitation/', InvitationView.as_view(), name='invitation'),
    path('organization/', OrganizationView.as_view(), name='organization'),
    path('manage_users/', ManageUserView.as_view(), name='manage_users'),
    path('register/<invitation_token>/', RegisterWithInvitationView.as_view(), name='register_with_invitation'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('active_user/<int:user_id>/', views.active_user, name='active_user'),
    path('upload_image/', views.image_upload_view, name='image_upload'),
    path('retrieve/', RetrieveImageView.as_view(), name='retrieve_image'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('User_Management.urls')),
    path('account/', include('Account_Management.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Account_Management/models.py
from django.db import models
from django.utils.crypto import get_random_string
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import Group
from User_Management.models import Profile, CustomUser


# Create your models here.
class Account(models.Model):
    ACCOUNT_STATUS_CHOICES = [
        ('active', 'Active'),
        ('expired', 'Expired'),
        ('fraud', 'Fraud'),
    ]

    COMPANY_SIZE_RANGE_CHOICES = [
        ('1-50', '1-50'),
        ('51-200', '51-200'),
        ('201-500', '201-500'),
        ('501-1000', '501-1000'),
        ('1001+', '1001+'),
    ]

    # profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    profile_video = models.URLField(max_length=255, null=True, blank=True)
    profile_logo = models.URLField(max_length=255, null=True, blank=True)
    company_name = models.CharField(max_length=255, null=True, blank=True)
    company_email = models.EmailField(max_length=255, null=True, blank=True)
    # account_status = models.CharField(max_length=255, choices=ACCOUNT_STATUS_CHOICES)
    company_summary = models.TextField(null=True, blank=True)
    company_industry = models.CharField(max_length=255, null=True, blank=True)
    company_size_range = models.CharField(max_length=255, null=True, blank=True, choices=COMPANY_SIZE_RANGE_CHOICES)
    company_website = models.URLField(max_length=255, null=True, blank=True)
    company_location = models.CharField(max_length=255, null=True, blank=True)
    company_domain = models.CharField(max_length=255, unique=True, default="")
    company_linkedin = models.URLField(max_length=255, null=True, blank=True)
    company_facebook = models.URLField(max_length=255, null=True, blank=True)
    company_twitter = models.URLField(max_length=255, null=True, blank=True)
    company_video_url = models.URLField(max_length=255, null=True, blank=True)
    viewed_employer_welcome = models.TextField(null=True, blank=True)
    viewed_employer_tutorial = models.TextField(null=True, blank=True)

    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['company_name']),
            # models.Index(fields=['account_status']),
            models.Index(fields=['company_industry']),
            models.Index(fields=['company_domain']),
        ]
        # def __str__(self):
    #     users = self.users.all()
    #     first_user = users[0].name if users else 'No users'
    #     return f'{first_user}, Organization: {self.organization}, Office: {self.office}, Department: {self.department}'


class Role(models.Model):
    ROLE_TYPE_CHOICES = [
        ('admin', 'Admin'),
        ('hiring_manager', 'Hiring_Manager'),
        ('recruiter', 'Recruiter'),
        ('coordinator', 'Coordinator'),
        ('sourcer', 'Sourcer'),
        ('external_reviewer', 'External_Reviewer'),
        ('sub_reviewer', 'Sub_Reviewer'),
    ]

    role_name = models.CharField(max_length=255, unique=True)
    role_type = models.CharField(max_length=255, choices=ROLE_TYPE_CHOICES)
    role_description = models.TextField(blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['role_type']),
        ]

    @receiver(post_save, sender='Account_Management.Role')
    def create_group_for_role(sender, instance, created, **kwargs):
        if created:
            group_name = f"{instance.role_type.capitalize()} Group"
            Group.objects.get_or_create(name=group_name)


class TeamInvitation(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name='team_invitations', blank=True, null=True)
    invited_email = models.EmailField()
    is_accepted = models.BooleanField(default=False)
    invited_by_user = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, null=True, blank=True, related_name='sent_invitations')
    invitation_token = models.CharField(max_length=32, unique=True, blank=True, null=True)
    role = models.ForeignKey(Role, on_delete=models.CASCADE, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['user']),
            models.Index(fields=['account']),
            models.Index(fields=['invited_email']),
            models.Index(fields=['is_accepted']),
            models.Index(fields=['role']),
        ]

    def save(self, *args, **kwargs):
        if not self.invitation_token:
            self.invitation_token = get_random_string(32)

        super().save(*args, **kwargs)


class AccountUserRelation(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user',)

Account_Management/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class InviteForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'shadow-border'}), required=True, label='Email')
    role_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'shadow-border'}), max_length=255)
    role_type = forms.ChoiceField(widget=forms.Select(attrs={'class': 'choice-field'}),
                                  choices=Role.ROLE_TYPE_CHOICES)
    
class OrganizationForm(forms.Form): 
    organization = forms.CharField(max_length=200, label='Company Name')


class UserInfoForm(forms.Form):
    first_name = forms.CharField(max_length=200, label='First name')
    last_name = forms.CharField(max_length=200, label='Last name')


class RegisterWithInvitationForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField(required=True, label='Email')
    role_type = forms.ChoiceField(choices=Role.ROLE_TYPE_CHOICES)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput())
    confirm_password = forms.CharField(max_length=128, widget=forms.PasswordInput(), label='Confirm Password')

Account_Management/views.py
import pdb
from django.contrib.auth import logout
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.list import ListView
from Account_Management.models import Account, TeamInvitation
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.views import View
from django.utils.crypto import get_random_string
from User_Management.models import CustomUser
from .forms import InviteForm, OrganizationForm, UserInfoForm
from User_Management.forms import UserCreationForm
from Account_Management.models import Profile, Account, AccountUserRelation
from django.template.loader import render_to_string
from .models import Role
from django.contrib.auth.models import Group


class AccountList(LoginRequiredMixin, ListView):
    model = Account
    context_object_name = 'Accounts'


class AccountSettingView(LoginRequiredMixin, View):
    model = Account
    context_object_name = 'edit_account'
    template_name = 'Account_Management/edit_account.html'

    def get_account_for_user(self, user):
        try:
            account_user_relation = AccountUserRelation.objects.get(user=user)
            return account_user_relation.account
        except AccountUserRelation.DoesNotExist:
            return None

    def get(self, request):
        current_user = request.user
        account = self.get_account_for_user(current_user)

        if not account:
            raise Http404("No account linked with the current user.")

        org_form = OrganizationForm(initial={'organization': account.company_name})
        user_info_form = UserInfoForm(
            initial={'first_name': current_user.first_name, 'last_name': current_user.last_name})
        user_groups = current_user.groups.all()
        user_roles = [group.name for group in user_groups]
        # account_user_relation = AccountUserRelation.objects.filter(user=current_user).first()
        # company_name = account_user_relation.account.company_name
        company_name = get_company_name(current_user)

        return render(request, self.template_name, {
            'account': account,
            'org_form': org_form,
            'user_info_form': user_info_form,
            'user_roles': user_roles[0],
            'company_name': company_name,
        })
        
    def post(self, request):
        org_form = OrganizationForm(request.POST)
        user_info_form = UserInfoForm(request.POST)
        if user_info_form.is_valid():
            current_user = request.user

            current_user.first_name = user_info_form.cleaned_data['first_name']
            current_user.last_name = user_info_form.cleaned_data['last_name']
            current_user.save()
            return redirect('account_management:edit_account')
        if org_form.is_valid():
            current_user = request.user
            account = self.get_account_for_user(current_user)

            if not account:
                raise Http404("No account linked with the current user.")
            # profile = Profile.objects.get(user=request.user)
            # account, created = Account.objects.get_or_create(profile=profile)
            account.company_name = org_form.cleaned_data['organization']
            account.save()
            return redirect('account_management:edit_account')
        
        #self.create_or_update_employer_basic_info(request)
        self.create_or_update_employer_info(request)
        #self.create_or_update_employer_summary(request)
        #self.create_or_update_employer_social_media(request)

        # return render(request, self.template_name, {'org_form': org_form})
        # Thinking of rediect user to organiztion, which view the changes.
        # return render(request, 'Account_Management/organization.html', {'org_form': org_form})
        return redirect('account_management:edit_account')

    def create_or_update_employer_info(self, request):
        if request.method == 'POST':
            # company_domain = request.POST.get("user_id")
            profile_video = request.POST.get("profile_video")
            profile_logo = request.POST.get("profile_logo")
            company_industry = request.POST.get("company_type")
            company_email = request.POST.get("contactEmail")
            company_location = request.POST.get("location")
            company_size_range = request.POST.get("company_size")
            company_website = request.POST.get("website")
            company_summary = request.POST.get("summary")
            company_linkedin = request.POST.get("linkedin")
            company_facebook = request.POST.get("facebook")
            company_twitter = request.POST.get("twitter")
            current_user = request.user
            account = self.get_account_for_user(current_user)

            try:
                account.profile_video = profile_video
                account.profile_logo = profile_logo
                account.company_industry = company_industry
                account.company_email = company_email
                account.company_location = company_location
                account.company_size_range = company_size_range
                account.company_website = company_website
                account.company_summary = company_summary
                account.company_linkedin = company_linkedin 
                account.company_facebook = company_facebook
                account.company_twitter = company_twitter
                account.save()
                messages.success(request, 'Your information has been successfully updated. ',
                                 extra_tags='info')
            except Account.DoesNotExist:
                messages.error(request, 'Account not found. Unable to update information.',
                               extra_tags='error')

        return redirect('account_management:organization')
        

class ConfigureView(LoginRequiredMixin, ListView):
    model = Account
    context_object_name = 'settings'

    def get_user_role(self, request, *args, **kwargs):
        current_user = request.user
        user_groups = current_user.groups.all()
        user_roles = [group.name for group in user_groups]
        return force_str(user_roles)

    def get_context_data(self, **kwargs):
        context = super(ConfigureView, self).get_context_data()
        user_roles = self.get_user_role(self.request)
        current_user = self.request.user
        account = getAccount(current_user)
        context['user_roles'] = user_roles
        context['account'] = account
        return context


class AddUserView(LoginRequiredMixin, View):
    model = TeamInvitation
    context_object_name = 'add_user'
    template_name = 'Account_Management/add_user.html'
    assign_org_url = reverse_lazy('account_management:edit_account')

    def get_account_for_user(self, user):
        try:
            account_user_relation = AccountUserRelation.objects.get(user=user)
            return account_user_relation.account
        except AccountUserRelation.DoesNotExist:
            return None

    # def dispatch(self, request, *args, **kwargs):
    #     try:
    #         current_account = self.get_account_for_user(request.user)
    #         if not current_account.company_name:
    #             messages.warning(request, "Please assign an company first.", extra_tags='manage')
    #             return redirect(self.assign_org_url)
    #     except AccountUserRelation.DoesNotExist:
    #         messages.warning(request, "Please assign an company first.", extra_tags='manage')
    #         return redirect(self.assign_org_url)
    #
    #     return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = InviteForm()
        # get role
        current_user = request.user
        account = getAccount(current_user)
        #user_role = self.get_user_role(self.request)
        user_groups = current_user.groups.all()
        user_roles = [group.name for group in user_groups]
        return render(request, self.template_name, {'form': form, 'user_roles': user_roles[0], 
                                                    'account': account}) #'user_role': user_role})

    def post(self, request):
        form = InviteForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            role_name = form.cleaned_data['role_name']
            role_type = form.cleaned_data['role_type']

            role = Role.objects.create(role_name=role_name, role_type=role_type)

            account_user_relation = AccountUserRelation.objects.get(user=request.user)
            account = account_user_relation.account

            # Generate the invitation token
            invitation_token = get_random_string(32)

            # Save the invitation with the token and other data
            invitation = TeamInvitation(
                account=account,
                invited_email=email,
                invited_by_user=request.user,
                role=role,
                invitation_token=invitation_token,
            )
            invitation.save()

            # Generate the registration link
            current_site = get_current_site(self.request)

            # Send invitation email with registration link
            subject = 'Invitation to Register'
            message = render_to_string('Account_Management/account_activation_email.html', {
                'domain': current_site.domain,
                'invitation_token': invitation_token,
            })
            from_email = 'yifandsb666@gmail.com'
            recipient_list = [email]
            send_mail(subject, message, from_email, recipient_list)

Account_Management/templates/Account_Management/account_activation_email.html
{% autoescape off %}
Hi {{ user }}, you have been invited to register on our website.
Please use the following link to register:
http://{{ domain }}{% url 'account_management:register_with_invitation' invitation_token=invitation_token %}
{% endautoescape %}

Account_Management/templates/Account_Management/account_list.html
{% extends 'User_Management/account_main.html' %}
{% load replace %}
{% load static %}
{% block content %}
    <head>
        <title>Configure | HireBeat</title>
        
    </head>
    <!-- Header Layout Content -->
    <div class="mdk-header-layout__content mdk-header-layout__content--fullbleed mdk-header-layout__content--scrollable page" style="padding-top: 60px;">


        <div class="container-fluid page__container page__heading d-flex align-items-center border-bottom  ">
            <h1 class="mb-0">Configure</h1>
{#            <img id="companyLogo" src="" alt="Not Found" onerror="this.src='{% static 'Hirebeat.jpeg' %}';" />#}
            <input type="hidden" id="accountName" value="{{ account.company_name }}">
        </div>
        <div class="container-fluid page__container">
            <div class="card-header card-header-large bg-light d-flex align-items-center">
                <div class="flex">
                    <h4 class="card-header__title">Organization</h4>
                </div>
                <div class="ml-auto">
                    <a href="{% url 'account_management:organization'%}" class="btn btn-light">Details</a>
                    {% if user_roles == "['Hiring_manager Group']" or user_roles == "['Admin Group']" %}
                        <a href="{% url 'account_management:edit_account'%}" class="btn btn-light">Edit</a>
                    {% endif %}
                </div>
            </div>
            {% if user_roles == "['Hiring_manager Group']" or user_roles == "['Admin Group']" %}
                <div class="card-header card-header-large bg-light d-flex align-items-center">
                    <div class="flex">
                        <h4 class="card-header__title">Users</h4>
                    </div>
                    <div class="ml-auto">
                        <a href="{% url 'account_management:manage_users' %}" class="btn btn-light">Manage</a>
                        <a href="{% url 'account_management:add_user' %}" class="btn btn-light">Invite</a>
                    </div>
            </div>
            {% endif %}
            <div class="card-header card-header-large bg-light d-flex align-items-center">
                <div class="flex">
                    <h4 class="card-header__title">Permission Policies</h4>
                </div>
                <div class="ml-auto">
                    <a href="#" class="btn btn-light">Manage</a>
                </div>
            </div>
            <div class="card-header card-header-large bg-light d-flex align-items-center">
                <div class="flex">
                    <h4 class="card-header__title">Email Settings</h4>
                </div>
                <div class="ml-auto">
                    <a href="#" class="btn btn-light">Manage</a>
                </div>
            </div>

        </div>



    </div>
    <!-- // END header-layout__content -->

    <!-- App Settings FAB -->
    <div id="app-settings">
        <app-settings layout-active="default" :layout-location="{
      'default': 'author-settings.html',
      'fixed': 'fixed-author-settings.html',
      'fluid': 'fluid-author-settings.html',
      'mini': 'mini-author-settings.html'
    }"></app-settings>
    </div>
<script src="https://www.gstatic.com/firebasejs/7.7.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.7.0/firebase-storage.js"></script>
<script>
   const firebaseConfig = {
        apiKey: "AIzaSyBxYu2sNjLgQsJJ7PwyK228DDdgg4rgSTw",
        authDomain: "hirebeat-561be.firebaseapp.com",
        projectId: "hirebeat-561be",
        storageBucket: "hirebeat-561be.appspot.com",
        messagingSenderId: "100708272950",
        appId: "1:100708272950:web:7fbab5c81409113efd8197",
        measurementId: "G-56Z0DL0SH3"
    };

   firebase.initializeApp(firebaseConfig);

   // 获取 Firebase Storage 中的图像 URL
   function getProfileImageURL() {
       const accountName = document.getElementById('accountName').value
       const imagePath = "logo/account/" + accountName;
       const storageRef = firebase.storage().ref();
       const imageRef = storageRef.child(imagePath);

      imageRef.getDownloadURL()
         .then((url) => {
            const profileImage = document.getElementById("profileImage");
            console.log(profileImage)
            profileImage.src = url;
         })
         .catch((error) => {
            console.error("Error getting download URL:", error);
         });
   }

   window.onload = function() {
      getProfileImageURL();
   };
</script>

{% endblock content %}

Account_Management/templates/Account_Management/add_user.html
{% extends 'Account_Management/account_main.html' %}
{% load static %}
{% load replace %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <title>Invite new user | HireBeat</title>
            <style>
                .form-group {
                    display: flex;
                    align-items: center;
                }

                .form-group label {
                    margin-right: 10px;
                    line-height: 32px;
                }



                .col.s14.z-depth-6.card-panel {
                    max-width: 500px;
                    margin: 0 auto;
                    padding: 20px;
                    justify-content: center;
                }

                input.button {
                    display: block;
                    width: 50%;
                    margin-top: 20px;
                    margin-left: 104.5px;
                    background-color: #2196F3;
                    border: 1px solid white;
                    padding: 10px;
                    color: white;
                    cursor: pointer;
                    
                }

                input.button:hover {
                    background-color: #1565C0;
                }

                
                .input-field.col.s12 select {
                    width: 73%; /* Adjust the width as needed */
                    margin-bottom: 10px;
                    margin-left: 7px;
                }


                .input-field.col.s12 input[type="text"] {
                    width: 72.5%;
                    margin-bottom: 10px;
                }

                .input-field.col.s12 input[type="email"] {
                    width: 73%;
                    margin-bottom: 10px;
                }

                .input-field.col.s12 input[type="text"][name="role_name"] {
                    width: 63.8%;
                    margin-bottom: 10px;
                    display: inline-block;
                    vertical-align: middle;
                }
                

                .custom-panel {
                    width: 490px; /* Adjust this value to set the desired height */
                    height: 300px;
                    vertical-align: center;
                  }

                .go_back_link {
                    cursor: pointer;
                    
                }

                .go_back_link:hover {
                    color: #1167C9;
                }

                .shadow-border {
                    border: none;
                    border-bottom: 1px solid transparent;
                    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
                    background-color: #F9F9F9;
                    width: 100%;
                    padding: 5px;
                }

            </style>
        </head>
        <body>
            <div class="mdk-header-layout__content mdk-header-layout__content--fullbleed mdk-header-layout__content--scrollable page" style="padding-top: 60px;">


                <div class="container-fluid page__container page__heading d-flex align-items-center border-bottom  ">
                    <h1 class="mb-0">Invite New User</h1>
{#                    <p>{{ user_roles|slice:"0:-5"|replace:"_"}}</p>#}
                </div>
                <div class="container-fluid page__container">
                    <div class="col s14 z-depth-6 card-panel custom-panel">
                        <div class="card card-body">
                            <form method="post" autocomplete="off">
                            {% csrf_token %}
                            <!-- <div class="input-field col s12">
                                <i class="material-icons prefix">person</i>
                                <label for="{{ form.name.id_for_label}}" style="vertical-align: middle;" id="name_label">Name:</label>
                                {{form.name}}
                            </div> -->
                            <br>
                            <div class="input-field col s12">
                                <i class="material-icons prefix">group</i>
                                <label for="{{ form.role_name.id_for_label}}" style="vertical-align: middle;" id="role_name_label">RoleName:</label>
                                {{form.role_name}}
                            </div>
                            <div class="input-field col s12">
                                <i class="material-icons prefix">group</i>
                                <label for="{{ form.role_type.id_for_label }}" style="vertical-align: middle;" id="role_type_label">Role: </label>
                                <select name="{{ form.role_type.name }}" id="{{ form.role_type.id_for_label }}" class="shadow-border">
                                    {% for role_choice in form.role_type.field.choices %}
                                        <option value="{{ role_choice.0 }}">{{ role_choice.1 }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="input-field col s12">
                                <i class="material-icons prefix">email</i>
                                <label for="{{ form.email.id_for_label}}" style="vertical-align: middle;" id="email_label">Email:</label>
                                {{form.email}}
                            </div>
                            <div class="mb-4">
                                <input class="button" type="submit" value="Invite" style="border: transparent">
                                <div class="row" style="margin-bottom: 15px "></div>
                                    <a onclick="function goBack() {window.history.back();}
                                goBack()" class="btn btn-light btn-block" style="width: 50%; margin: auto;">Go Back</a>
                                </div>
                            
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            
            
        </body>

    </html>

{% endblock content %}

Account_Management/templates/Account_Management/basic_info.html
<!DOCTYPE html>
<html>
<head>
    <title>Create or Update Employer Basic Info</title>
</head>
<body>
    <h1>Create or Update Employer Basic Info</h1>
    <form method="post" action="/account/create_or_update_employer/">
        {% csrf_token %}
        <label for="user_id">Company Domain:</label>
        <input type="text" name="user_id" required><br>
        
        <label for="company_type">Company Industry:</label>
        <input type="text" name="company_type" required><br>
        
        <label for="contactEmail">Contact Email:</label>
        <input type="email" name="contactEmail" required><br>
        
        <label for="location">Location:</label>
        <input type="text" name="location" required><br>
        
        <label for="company_size">Company Size:</label>
        <br><input type="text" name="company_size" required><br><br>
        
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</body>
</html>

Account_Management/templates/Account_Management/delete_account_success.html
{{ Deleted !!!}}

Account_Management/templates/Account_Management/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
{#    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}

    <style>
        html,
            body {
                height: 100%;
            }
            html {
                display: table;
                margin: auto;
            }
            body {
                display: table-cell;
                vertical-align: middle;
            }

            .layout-login-centered-boxed {
                height: initial;
              }

              .layout-login-centered-boxed__form {
                padding: 2rem;
                position: relative;
              }

              @media screen and (min-width: md) {
                .layout-login-centered-boxed {
                  display: flex;
                  justify-content: center;
                  align-items: center;
                }

                .layout-login-centered-boxed__form {
                  max-width: 26rem;
                  min-width: calc(320px + 3rem * 2);
                  padding: 3rem;
                }
              }
    </style>
</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>